use_frameworks!

target 'AKAlipayManager_Example' do
  pod 'AKAlipayManager', :path => '../'
  
  #pod 'AKAlipaySDK', :git => 'git@github.com:ArtisanKid/AKAlipaySDK.git'
  pod 'AKAlipaySDK', :path => '../../AKAlipaySDK'
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
  end

  target 'AKAlipayManager_Tests' do
    inherit! :search_paths

    
  end
end
